### ISSUE TITLE
Gene symbol aliases

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/antibody-api#103]
@ChuckKollar 

Currently the gene symbol `Target Name` field can be any value provided by a person uploading data.  This is causing confusion for end users who may not think of the gene with the same name or symbol.

To fix this issue we'd like to:
 - Store and allow faceted search (left search lists) of [HGNC](https://www.genenames.org/) `Approved Symbols` only
 - When searching via the keyword search feature (Search bar/input box at the top of the UI) search across all potential names reported by HGNC which, other than `Approved Symbols` includes `Previous Symbols` and `Alias Symbols`
 
 To this end I propose:
  - Change the current field `Target Name` to `Target Symbol`
  - At AVR import time resolve any symbols included as `Target Symbol` to the HGNC `Approved Symbol` by searching HGNC `Approved Symbols`, `Previous Symbols` and `Alias Symbols` using the UBKG service.  If the symbol provided during input can't be found in HGNC then fail validation for the import.
  - Add an additional, non-displayed field in Elasticsearch to each AVR document, `target_aliases` that includes this list of all alternate gene symbols, called `alternate_target_symbols`, which will hold the list of any HGNC `Previous Symbols` and/or `Alias Symbols` associated with the `Approved Symbol`.
  - The new `alternate_target_symbols` field in Elasticsearch should then be included when doing a search via the Search bar at the top of the UI.
  
#### Add'l Info
 - A suggested UBKG endpoint to support this new feature is recorded in [UBKG API issue #45](https://github.com/x-atlas-consortia/ubkg-api/issues/45).  This endpoint (or similar) will need to be implemented as a dependency to this issue.
 - An example of the HGNC information can be seen in the record for the [MMRN1 gene symbol](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:7178) where:
   - the `Approved Symbol` is MMRN1
   - the `Previous Symbols` include MMRN
   - the `Alias Symbols` include ECM, EMILIN4 and GPIa

**Comment by ChuckKollar** [comment]
I think that it makes sense to keep the 'target_name' field in the .csv file only because it can be different from what is eventually the 'target_symbol', and so the user might get confused when the value that they entered gets changed on them.

**Comment by ChuckKollar** [comment]
I am also adding the 'target_symbol' to the list of things that can be searched on 'target_aliases' for two reasons:
1) it's simpler to have one field to search on,
2) if the target_symbol' somehow gets changed to one of the 'previous symbols' then it can still be searched on in older data. With this in mind there is no current mechanism for rebuilding the 'previous symbols' in ElasticSearch after several changes have been made by the keepers of the data names.

**Comment by shirey** [comment]
> I think that it makes sense to keep the 'target_name' field in the .csv file only because it can be different from what is eventually the 'target_symbol', and so the user might get confused when the value that they entered gets changed on them.

@ChuckKollar I disagree because there are fields in HGNC that refer to "name", which we aren't using-- whereas the three fields that we are dealing with all have "symbol" in the name.  Also, some domain experts who I have talked to make the distinction between "name" and "symbol"- where name refers to a longer human readable name or description and symbol is usually more like a code.

**Comment by ChuckKollar** [comment]
OK... So target_name goes and is replaced EVERYWHERE by target_symbol even though the target_symbol in the .csv file could be different from the target_symbol that ends up in the database.

Yes, target_aliases only shows up in the ElasticSearch data and is only used by the search at the top of the UI as per above. target_aliases never shows up on the GUI or in the downloaded .csv file.
