### ISSUE TITLE
Add `cell_line` and `cell_line_ontology_id` fields

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/antibody-api#105]

**Comment by ChuckKollar** [comment]
Add to .csv file and GUI.

**Comment by ChuckKollar** [comment]
The validation for "cell_line_contology_id" is the same as for UBERON except it should use the "Cell line ontology".
There validation for the name 'cell_line' can be a combination of upper and lowercase and numbers (don't validate this).

These are the 2 new columns in the AVR.csv template that relates mostly to us needing to harmonize with the 110 original AVR
cell_line	         cell_line_ontoloty_id
HeLa cell	CLO:0003684
MCF7 cell	CLO:0007606
MCF7 cell	CLO:0007606
HeLa cell	CLO:0003684

**Comment by emquardokus** [comment]
Related: https://github.com/hubmapconsortium/antibody-api/issues/117
