### ISSUE TITLE
AVR website: AVR.csv change dilution to dilution_factor

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/antibody-api#112]
@ChuckKollar
For the AVR website AVR.csv upload validation, please change the field name from dilution to dilution_factor.
Expected column value: whole number

Reason:  we continually have had problems with submissions from authors where the "smart" spreadsheet programs alter the values when provided as 1:100 or 1/100. If we simply use 100 and designation dilution factor, this means the same thing and is less problematic. Expected column value: whole number

**Comment by ChuckKollar** [comment]
This should be done and on DEV
