### ISSUE TITLE
AVR website: protocol_doi field name

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/antibody-api#114]
use protocol_doi and NOT protocols_doi or protocols.io
protocol_doi can have comma delimited list of protocol doi

**Comment by ChuckKollar** [comment]
This should be done and is available on DEV

**Comment by emquardokus** [comment]
@ChuckKollar Friday 7-21-2023 
Testing with .csv that had comma delimited protocol doi and it rejected.
- [ ] ADD support for protocol_doi can have comma delimited list of protocol doi
