### ISSUE TITLE
AVR website: change the heading of "Author ORCiD iD" to "Author ORCiDs"

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/antibody-api#115]
On website, change the heading of "Author ORCiD iD" to "Author ORCiDs"
From AVR.csv upload, field name is called : author_orcids
Related github issue: https://github.com/hubmapconsortium/antibody-api/issues/107

**Comment by emquardokus** [comment]
@ChuckKollar

**Comment by ChuckKollar** [comment]
This should be done and available on DEV
