### ISSUE TITLE
AVR website: change download .csv button action and naming

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/antibody-api#116]
Original button name: download selected AVR information as .csv
**New button name: Download AVR Information as CSV**
Original action: download selected AVR information as .csv only downloaded fields that author selected plus the default fields.
**New action: download all fields in .csv as default**

**Comment by emquardokus** [comment]
@ChuckKollar

**Comment by ChuckKollar** [comment]
This should be done and available on DEV
