### ISSUE TITLE
AVR website: cell_line field validation dependency

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/antibody-api#117]
When validating AVR.csv, either organ field or cell_line field will have a value, but not both at once. 
I

**Comment by emquardokus** [comment]
related issue: https://github.com/hubmapconsortium/antibody-api/issues/105

**Comment by emquardokus** [comment]
@ChuckKollar

**Comment by ChuckKollar** [comment]
This is done and should be available on DEV
