### ISSUE TITLE
AVR website: search page dialog box update

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/antibody-api#119]
**search page dialog box update**

1) Dialog box currently says "set or clear all" should be "select or clear all" (see screenshot of current dialog)
<img width="269" alt="Screenshot 2023-07-20 at 1 28 12 PM" src="https://github.com/hubmapconsortium/antibody-api/assets/47257000/c624c934-4662-4f56-ac47-4762c2cafc64">

2)Fix issue with  Default dialog box has "Antigen Retrieval" selected. Nothing should be selected as default.

3) Dialog box should contain these fields matched with AVR.csv updated template: NOTE one modification from yesterday's discussion would be organ_uberon to organ_uberon_id 

**6 Default fields displayed across the top: **
Target Symbol, Uniprot#, Clonality, Method, Tissue Preservation, Validation Report

**23 field names total not in the default display on page:**
(Changes denoted in bold)
Antigen Retrieval
Author ORCiDs
Catalog#
Cell Line
Cell Line Ontology ID
Concentration
Conjugate
Cycle#
**Dilution Factor**
Fluorescent Reporter
HGNC ID
Host
Isotype
Lot#
Manuscript DOI
OMAP ID
Organ
**Organ UBERON ID**
Protocol DOI
Recombinant
RRID
Vendor
Vendor Affiliation

**Comment by emquardokus** [comment]
@ChuckKollar

**Comment by emquardokus** [comment]
Friday 7-21-2023

**Comment by ChuckKollar** [comment]
It uses cookies to determine if you have had any of the "Configure Columns" selected.
Also "submitter email" is not in the .csv file but collected when the user Adds AVRs.

**Comment by ChuckKollar** [comment]
If CLONE_ID is not to be a default field then it needs to be added to the "Configuration Columns" list.
