### ISSUE TITLE
OMAP linkage from AVRs

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/antibody-api#148]
Link to the OMAP page (open in a new tab) from the OMAP entries (column) in the search results table.  To accomplish this:
  - Make the OMAP column display by default (currently it is hidden by default)
  - Link the individual OMAP entries to the (P)URLs defined mapped in [HRA7threleasetoUBKG-June2024PurlsOMAPs.xlsx](https://github.com/hubmapconsortium/antibody-api/files/13229463/HRA7threleasetoUBKG-June2024PurlsOMAPs.xlsx) (create a hard-coded json or other from this to use with AVR).
  - If an OMAP link hasn't been defined in the map, don't link that entry.
  
The hard coded OMAP mapping will eventually be replaced with calls to UBKG, but this information isn't available in the HRA (hosted in UBKG) yes.  We'll track this switch in #143

**Comment by yuanzhou** [comment]
Addressed and tested on DEV. Waiting on Ellen's green light to release to PROD via a draft PR: https://github.com/hubmapconsortium/antibody-api/pull/152
