### ISSUE TITLE
Store and display HuBMAP IDs for all AVRs

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/antibody-api#149]
Users of the AVR system have asked for HuBMAP IDs associated with individual AVR records.  It appears as though these IDs are already being generated and stored in the UUID system. 

  - Ensure the HuBMAP_ID for each AVR is stored in the database and elasticsearch at the time that the AVR is imported.
  - Make these ids searchable via the keyword/typed search 
  - Add a column, displayed by default, to the search result list to show these ids
  - Make sure all HuBMAP IDs for existing AVRs are added to the database/elasticsearch (can obtain transform to HuBMAP IDs  the UUID system field `uuids_attributes.base_id)

**Comment by ChuckKollar** [comment]
It appears that the 'uuid' is being saved, but not the 'hubmap_id'. I will need to fix this.
