### ISSUE TITLE
[AVR] Configurable banner message

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/antibody-api#160]
For announcement purposes, we need a new config item that can be parsed by the App and shows a banner message without rebuilding the image.

**Comment by ChuckKollar** [comment]
Zhou Yuan [1:40 PM] Feb 19, 2024
Here are some quick examples. Essentially we wanted to have a config item that can take some HTML so show as a banner on top of the AVR site when we need to announce something. Depending on how AVR handles the UI piece vs Python antibody-api, it can read from the Python app config or it can be part of the React UI with some dynamic loading from a public asset, whichever works easier for you. Both Lisa-Ann and Jes had hard times loading from a config file during runtime, so we don't need to rebuild a new docker image for any banner update. They ended up with using some React public asset file for such use cases, not ideal but serves for the purpose.
