### ISSUE TITLE
Update AVR values

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/antibody-api#169]
Based on the attached spreadsheet (will be uploaded here or in a note below soon, by Ellen) update the values of the fields specified in the AVR database (and indices).

**Comment by emquardokus** [comment]
50 entries updated April 30, 2024 of 197
The spreadsheet includes the published HuBMAP IDs and the filepath for pdf as it appears in downloaded csv from AVR website.
Involving OMAP-1 Lymph node, OMAP-10 Palatine tonsil, OMAP-12 retina, OMAP-4 skin, OMAP-6 pancreas, OMAP-9 kidney
Typo Cell Signalling Technology to Cell Signaling Technology
Typo MiliporeSigma  to MilliporeSigma
Standardize Millipore to MilliporeSigma
Standardize Sigma to MilliporeSigma
Standardize Alexa Fluor 488 to AF488
Standardize 1% PFA Fixed Frozen to 1% PFA fixed frozen
Correct MACSima refers to instrument to MICS refers to technology
Standardize iFluor 594 to iF594
Standardize PE-iFluor 594 to PE-iF594

**Complete record for 50 AVRs that contain changes--has all fields**
[AVRWebsiteUpdates4-30-2024-CompleteRecordChangedFieldsupload.csv](https://github.com/hubmapconsortium/antibody-api/files/15165342/AVRWebsiteUpdates4-30-2024-CompleteRecordChangedFieldsupload.csv)

**Only fields that changed for 50 AVRs**
[AVRWebsiteUpdates4-30-2024ChangedFieldsOnlyupload.csv](https://github.com/hubmapconsortium/antibody-api/files/15165347/AVRWebsiteUpdates4-30-2024ChangedFieldsOnlyupload.csv)

**Fields with changes:**
vendor_name
conjugate
method	
tissue_preservation
fluorescent_reporter
**filed included for identification:**
antibody_hubmap_id

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/antibody-api/pull/173

**Comment by ChuckKollar** [comment]
I copied the database from PROD to DEV and ran the script over DEV using the "Only fields that changed for 50 AVRs" from Ellen above, and it appeared to work. I am waiting from confirmation from Ellen on this.
