### ISSUE TITLE
Update to lasted vsn of Searchkit

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/antibody-api#182]
Update Searchkit to latest version

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/antibody-api/pull/188

I spent quite a bit of time trying to upgrade to Searchkit v4. The problems that I experienced were mostly related to the fact that the look and feel would be quite different. It would also involve quite a bit more time to get it right. I decided to upgrade packages for Searchkit v2, fix some urls that were no longer valid, and track down some bugs that showed up in the console of the browser debugger.
