### ISSUE TITLE
Protect reindex endpoint behind gateway

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/antibody-api#29]
Protect the reindex endpoint at the gateway so only users in the HuBMAP-Data-Admin can call it

**Comment by yuanzhou** [comment]
The `PUT /reindex-all` call is already protected. However, the individual `PUT /reindex/<uuid>` call doesn't require Data-Admin access, it only requires Read access. 

@shirey were you referring to the reindex-all or individual reindex call in this card originally?

**Comment by shirey** [comment]
@yuanzhou This was for reindex-all so closing.
