### ISSUE TITLE
antibody upload page work for multiple .pdf

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/antibody-api#34]
The current upload page only allows you to upload one .pdf file. This is a problem if there are multiple .pdf files references in the .csv file.

The task here it to allow the user to upload multiple .pdf files after determining which files need to be uploaded.

So this actually worked. The problem was that I was using a broken .csv file and it was dying there.

**Comment by gorandev** [comment]
Page allows several PDF files! I've tested that a lot.
