### ISSUE TITLE
Deployment Rights on Test

### ISSUE THREAD

**Issue by shaabans** [hubmapconsortium/antibody-api#4]
Bill, would it be possible to provide us with rights to deploy on Test, then your team can move to Prod?

**Comment by shirey** [comment]
@shaabans and @gorandev Rethinking the discussion that we had on Slack: https://hubmapconsortium.slack.com/archives/C023N92R8MP/p1626977206052400-- your only dependency on our services is our id server, [uuid-api](https://github.com/hubmapconsortium/uuid-api), you are welcome to use our existing DEV id service (https://uuid-api.dev.hubmapconsortium.org/status).  Given this if you test locally against our DEV service, then when feature complete and fully tested locally we will install to our TEST infrastructure (usually Zhou) for final testing and eventual

Additionally I will give Juaquin (and anyone else who needs it) access to deploy to our DEV infrastructure in case you need to do non-local integration testing.

**Comment by shaabans** [comment]
Getting close, will close when we have first deployment behind us.
