### ISSUE TITLE
Probing the .pdf file for information rather than counting on the information in the .csv file at the time of ingest

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/antibody-api#63]
Ellen Quardokus
This RRID number AB_10563656 shows up twice, but for two different antibodies: Anti-LYVE1 antibody [EPR21857 and HLA-DR antibody [EPR3692]. Only the HLA-DR antibody [EPR3692] entry is correct for that RRID.
I looked up the RRID at https://scicrunch.org/resources/Antibodies/search?q=RRID%20AB_10563656&l=RRID%20AB_10563656
It’s for  HLA-DR antibody [EPR3692], Abcam http://antibodyregistry.org/AB_10563656 Cite this (Abcam Cat# ab92511, RRID:AB_10563656)

When you look at the actual PDF report for Anti-LYVE1 antibody [EPR21857, it provides the right RRID as: RRID: AB_2884014
How are the AVRs uploaded to provide the RRID field?  I thought it would be harvested from the PDF report? Answer: No, it's from the .csv file.
Anyhow, this one is somehow a mistake.
scicrunch.orgscicrunch.org
RRID | Searching for RRID AB_10563656 in Antibodies
Results for the query 'RRID AB_10563656' in resources Antibodies across 1 data views.

**Comment by shirey** [comment]
Given the above, and that we have a good working solution in place, I'm going to close this issue.  "Won't Do"
