### ISSUE TITLE
Get details on HubMAP ID service

### ISSUE THREAD

**Issue by gorandev** [hubmapconsortium/antibody-api#7]
There's a HubMAP ID service to generate UUIDs for all new entities. We would like to mock this locally so we can develop faster.

**Comment by shirey** [comment]
https://hubmapconsortium.slack.com/archives/C023N92R8MP/p1624157486021700

**Comment by gorandev** [comment]
> https://hubmapconsortium.slack.com/archives/C023N92R8MP/p1624157486021700

That link is not working for me -- could you paste the conversation here? Thank you!

**Comment by shaabans** [comment]
Getting close here, and mocking locally.
