### ISSUE TITLE
CD3 uploaded under Liz McDonough (GE) email address

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/antibody-api#76]
From: McDonough, Liz (GE Research, US) <elizabeth.mcdonough@ge.com>
Date: Thursday, September 8, 2022 at 5:10 PM
To: Kollar, Charles P. <charles.kollar@pitt.edu>
Subject: RE: HuBMAP Antibody Validation Reports

It’s working! Is there any way to delete one? I swapped the target/antibody columns for the CD3 I uploaded. if not, not a big deal.
 
Thanks again.
 
Best,
Liz

**Comment by shirey** [comment]
Latest release will include a full reload of the DB which will fix this.  Closing.
